### ISSUE TITLE
Maintaining repo

### ISSUE THREAD

**Issue by cpaczek** [DustinBryant/MMM-Ring#14]
Hi,
I have a ring doorbell and I just got my smart mirror up and working, I have lots of experience with nodejs electron and I am also looking to learn a lot more about MMM's and I could take over this repo if you want, I am currently working on implementing on popping up the video with motion on my own fork which I will make a pull request in the next day or so, asuming the feature is not on your local branch.

I do have some questions on how you/why you did things the way you did.

In node_helper.js on line 172 you call camera.streamVideo and pass in a whole bunch of stuff but I could not find the docs for it,
According to the ring api docs you would use 

```
camera.startVideoOnDemand() // ask the camera to start a new video stream 

camera.createSipSession() // creates a new SipSession which allows you to control RTP flow
```
but not streamVideo. My best guess is it uses ffmepg instead of native stuff. But i'm not sure how you interact with the ffmpeg app through node without doing some sort of import unless it's the ring api that requires it.

My next question why didn't you use a variable keyword like const let or var for a lot of the variable declaration is it just to make the code a bit nicer? or is there a reason?

Next question is why are you storing the RING 2fa code in a temp env file instead of just a in memory variable it seems it would be easier to store in json. Unless you are actually writing to the module config which I can't figure out how you would do that.

**Comment by cpaczek** [comment]
My pull request is now live!

**Comment by DustinBryant** [comment]
Thanks for the PR. I'm slammed right now with work stuff but I'll do my best to answer your questions tomorrow when I get a chance to re-evaluate the existing code I wrote.

**Comment by DustinBryant** [comment]
**camera.StreamVideo vs camera.StartVideoOnDemand**
His documentation doesn't have anything related to camera.StreamVideo but it is a valid call for the camera. The main differences are, StartVideoOnDemand is a post REST API action which doesn't provide back the stream. It just tells your camera to start recording. Whereas, StreamVideo allows you to provide FFMPEG data and then store the stream videos at a specific location. 

Take a look at this file:
https://github.com/dgreif/ring/blob/master/api/ring-camera.ts

Line 284 (startVideoOnDeman()) - as you can see it is very limited in what it does. 
Line 605 (streamVideo()) - This is where the magic happens

Your assumption about interaction with FFMPEG app being required by the ring api is correct.

**Variable keywords**
I actually do use const quite a bit in here. I then use **this** to scope to the module. Maybe I could have predefined those variables outside the method/function calls to make it more obvious but I'm not opposed to let or var. Maybe you have a specific example you're talking about here so I can shed more light on it?

**2fa**
Great question.. As I no longer had a Ring device I wasn't able to test alternatives. I wanted to get this working for everyone else so I went with the examples of ring-client-api and utilized dotenv as was being used there (see https://github.com/dgreif/ring/blob/master/examples/api-example.ts).

You may want to test this out with storing the token in memory to see if you can get it working and then remove that dotenv dependency if you have success.

Thanks for deciding to maintain this repository. I'm sure the people who use this will appreciate it. If there is something that you feel makes the code more readable or changes you'd like to see then have at it. This module relies heavily on the ring-client-api so it may make sense for you to follow the changes of that github repo. dgreif updates it regularly and there are usually updates that fix some issues people may have with this magic mirror module. 

Our lives would have been much easier if Ring had just created some API for developers to use, but since that isn't the case the work of dgreif reverse engineering the Ring App has given us this ability. The only issue being, Ring at any point can change how they do things which can easily break this third party api. This has happened on many occasions, so be aware.

**Comment by cpaczek** [comment]
Thanks for the explanations, should be much easier to maintain now.
