### ISSUE TITLE
2F Token expires

### ISSUE THREAD

**Issue by McMornan** [DustinBryant/MMM-Ring#7]
Hi,

thanks for that great addition to MagicMirror! Ususally it works like a charm ... however every few weeks I need to recreate the 2F token - any idea why ? (the old one is no longer accepted - I have not figured out any form of outside relation or regularity yet)

thanks,
Lars

**Comment by DustinBryant** [comment]
Just updated this repository to require 2F Refresh Token as well as automating the process of automatically getting a new Refresh Token when the old one expires.

In order to get this update navigate to the MMM-Ring directory within MagicMirror/modules and perform the following:

```git pull```
```npm install```

If you need more information on the Refresh Token you can find it here: https://github.com/DustinBryant/MMM-Ring/wiki/Refresh-Tokens
